apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          # Replaced in CI: sed -i "s|IMAGE_PLACEHOLDER|<account>.dkr.ecr.<region>.amazonaws.com/eks-demo-dev-app:<tag>|" k8s/deployment.yaml
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: APP_VERSION
              value: "IMAGE_TAG_PLACEHOLDER"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
